### PR TITLE
Extract model year and updated manufacturers dataset

### PR DESCRIPTION
**Pull request by micaiah-effiong**
- added prettier config
 
- added function to get a model year for the vehicle
 
- update manufacturers' dataset [reference](https://en.wikipedia.org/wiki/Vehicle_identification_number)

### CODE REVIEW

**Comment by micaiah-effiong** [comment]
@frankely please take a look at this merge request

**Comment by frankely** [comment]
Looks great, just a minor comment, style-wise, could we use single quotes and re run the linter? @micaiah-effiong

**Comment by micaiah-effiong** [comment]
@frankely linting and formatting has been fixed

**Review by frankely — APPROVED** [review]
great work!

**Pull request merged**
