### PR TITLE
Feature/add checksum param

### PR DESCRIPTION
**Pull request by darwin2k**
added the checksum value as optional param.
In my usecase:  a german vehicle registration document has a special checksum value which is not  included in the VIN.

I also added a License file. Merge when you are ok with it to license it MIT.

### CODE REVIEW

**Comment by frankely** [comment]
It looks like there are some conflicts in the index.js, you might want to rebase your branches since I updated some syntax in most of the files a few days ago.

**Comment by frankely** [comment]
Could it be possible that you rebase your branch?

**Comment by darwin2k** [comment]
I resolved the conflicts

**Comment by darwin2k** [comment]
hi @frankely  - whats the status? any issues with the PR?

**Review by frankely — APPROVED** [review]

**Comment by frankely** [comment]
All good, I just merged it!

**Pull request merged**
